// ┌────────────────────────────────────────────────────────────────────────────────────┐
// │ Default BWR Configuration - Exact Port from Python                                 │
// └────────────────────────────────────────────────────────────────────────────────────┘

import { BWRConfig } from './config-types';

export const DEFAULT_BWR_CONFIG: BWRConfig = {
  general: {
    width: 1920,
    height: 1080,
    template: "plotly_white",
    background_image_path: "./brand-assets/bg_black.png",
  },
  colors: {
    background_color: "#1A1A1A",
    primary: "#5637cd",
    bar_default: "#5637cd",
    hbar_positive: "#5637cd",
    hbar_negative: "#EF798A",
    default_palette: [
      "#5637cd",
      "#779BE7",
      "#8F7BE1",
      "#EF798A",
      "#C0B9D8",
      "#8a7cff",
      "#F3A712",
      "#9f95c6",
      "#d62728",
      "#9467bd",
      "#8c564b",
      "#e377c2",
      "#7f7f7f",
      "#bcbd22",
      "#17becf",
    ],
  },
  fonts: {
    normal_family: "Maison Neue, Inter, sans-serif",
    bold_family: "Maison Neue Medium, Inter, sans-serif",
    title: { size: 51.6, color: "#ededed" },
    subtitle: { size: 21.6, color: "#adb0b5" },
    axis_title: { size: 16.8, color: "#ededed" },
    tick: { size: 21.6, color: "#ededed" },
    legend: { size: 24.0, color: "#ededed" },
    annotation: { size: 17.4, color: "#9f95c6" },
    table_header: { size: 24, color: "#ededed" },
    table_cell: { size: 20, color: "#ededed" },
  },
  watermark: {
    available_watermarks: {
      "Blockworks Research": "./brand-assets/bwr_white.svg",
      "Blockworks Advisory": "./brand-assets/bwa_white.svg",
    },
    selected_watermark_key: "Blockworks Research",
    default_use: true,
    chart_opacity: 1.0,
    chart_layer: "above",
    chart_x: 1.012,
    chart_y: 1.275,
    chart_sizex: 0.20,
    chart_sizey: 0.20,
    chart_xanchor: "right",
    plotly_table_options: {
      use_default_path: true,
      x: 1.012,
      y: 1.275,
      sizex: 0.20,
      sizey: 0.20,
      opacity: 1.0,
      layer: "above",
      xanchor: "right",
      yanchor: "top",
    },
  },
  layout: {
    margin_l: 120,
    margin_r: 70,
    margin_t_base: 108,
    margin_b_min: 0,
    plot_area_b_padding: 0,
    title_x: 0.035,
    title_padding: 100,
    hovermode: "x unified",
    hoverdistance: 100,
    spikedistance: 1000,
    table_margin_l: 67,
    table_padding_below_source_px: 20,
  },
  legend: {
    bgcolor: "rgba(255, 255, 255, 0)",
    bordercolor: "rgba(255, 255, 255, 0)",
    borderwidth: 0,
    font_family: "Maison Neue",
    font_color: "#282829",
    font_size: 14.4,
    orientation: "h",
    yanchor: "top",
    y: -0.15,
    x: 0.01,
    xanchor: "left",
  },
  annotations: {
    annotation_font_size: 17.4,
    annotation_color: "#9f95c6",
    source_y: 1.37,
    source_x: 1.012,
    source_anchor: "right",
    subtitle_yshift: -12,
    subtitle_font_size: 21.6,
    subtitle_color: "#adb0b5",
  },
  axes: {
    x_numeric_tickformat: "",
    gridcolor: "#404040",
    zerolinecolor: "#404040",
    showgrid_x: false,
    showgrid_y: true,
    showline: false,
    linecolor: "#404040",
    linewidth: 1,
  },
  plot_specific: {
    scatter: {
      use_background_image: true,
      mode: "lines+markers",
      line_width: 4,
      marker_size: 8,
      opacity: 1.0,
    },
    bar: {
      use_background_image: true,
      opacity: 1.0,
      bargap: 0.15,
    },
    horizontal_bar: {
      use_background_image: true,
      opacity: 1.0,
      bargap: 0.15,
      sorting: {
        enabled: true,
        ascending: false,
      },
    },
    multi_bar: {
      use_background_image: true,
      opacity: 1.0,
      bargap: 0.15,
      bargroupgap: 0.1,
    },
    stacked_bar: {
      use_background_image: true,
      opacity: 1.0,
      bargap: 0.15,
    },
    metric_share_area: {
      use_background_image: true,
      opacity: 0.8,
      smoothing: {
        enabled: false,
        window: 7,
      },
    },
    table: {
      use_background_image: false,
      row_height: 60,
      header_height: 70,
      stripe_color: "#2A2A2A",
      border_color: "#404040",
      border_width: 1,
    },
  },
};