version: '3.8'

services:
  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./src:/app/src  # Mount bwr_tools source
    environment:
      - PYTHONPATH=/app/src
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    networks:
      - bwr-network

  # Next.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Prevent overwriting node_modules
      - /app/.next  # Prevent overwriting build cache
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - bwr-network

  # Optional: Streamlit App
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app/src
    command: streamlit run app.py --server.port 8501 --server.address 0.0.0.0
    profiles:
      - full  # Only runs when --profile full is used
    networks:
      - bwr-network

  # Optional: Redis for session management
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - bwr-network
    profiles:
      - full

networks:
  bwr-network:
    driver: bridge