// ┌────────────────────────────────────────────────────────────────────────────────────┐
// │ BWR Configuration - Exact match to Python bwr_plots                                │
// └────────────────────────────────────────────────────────────────────────────────────┘

import { BWRConfig } from './types';

// Default configuration dictionary for all BWR plots
// CRITICAL: These values must match Python EXACTLY for pixel-perfect output
export const DEFAULT_BWR_CONFIG: BWRConfig = {
  general: {
    // Figure size and style
    width: 800,
    height: 400,
    template: 'plotly_white',
    background_image_path: '', // Disabled temporarily
  },
  colors: {
    background_color: '#1A1A1A',
    primary: '#5637cd', // Kept for clarity, used for bar_default/hbar_positive
    bar_default: '#5637cd',
    hbar_positive: '#5637cd',
    hbar_negative: '#EF798A',
    default_palette: [
      '#5637cd',
      '#779BE7',
      '#8F7BE1',
      '#EF798A',
      '#C0B9D8',
      '#8a7cff',
      '#F3A712',
      '#9f95c6',
      '#d62728',
      '#9467bd',
      '#8c564b',
      '#e377c2',
      '#7f7f7f',
      '#bcbd22',
      '#17becf',
    ],
  },
  fonts: {
    normal_family: 'Maison Neue, Inter, sans-serif',
    bold_family: 'Maison Neue Medium, Inter, sans-serif',
    title: { size: 51.6, color: '#ededed' },
    subtitle: { size: 21.6, color: '#adb0b5' },
    axis_title: { size: 16.8, color: '#ededed' },
    tick: { size: 21.6, color: '#ededed' },
    legend: { size: 24.0, color: '#ededed' },
    annotation: { size: 17.4, color: '#9f95c6' },
    // Table-specific fonts (optional, fallback to title/tick if not present)
    table_header: { size: 24, color: '#ededed' },
    table_cell: { size: 20, color: '#ededed' },
  },
  watermark: {
    available_watermarks: {
      'Blockworks Research': 'brand-assets/bwr_white.svg',
      'Blockworks Advisory': 'brand-assets/bwa_white.svg',
    },
    selected_watermark_key: 'Blockworks Research',
    default_use: true,
    chart_opacity: 1.0,
    chart_layer: 'above',
    chart_x: 1.012,
    chart_y: 1.275,
    chart_sizex: 0.20,
    chart_sizey: 0.20,
    chart_xanchor: 'right',
  },
  layout: {
    margin_l: 120,
    margin_r: 70,
    margin_t_base: 108, // 108
    margin_b_min: 0, // 24
    plot_area_b_padding: 0, // -36
    title_x: 0.035,
    title_padding: 100,
    hovermode: 'x unified',
    hoverdistance: 100,
    spikedistance: 1000,
  },
  legend: {
    bgcolor: 'rgba(255, 255, 255, 0)',
    bordercolor: 'rgba(255, 255, 255, 0)',
    borderwidth: 0,
    font_family: 'Maison Neue',
    font_color: '#282829',
    font_size: 14.4,
    orientation: 'h',
    yanchor: 'top',
    y: -0.138,
    xanchor: 'left',
    x: 0.0,
    title: '',
    itemsizing: 'trace',
    itemwidth: 36,
    marker_symbol: 'circle',
    marker_size: 12,
    traceorder: 'reversed',
  },
  annotations: {
    default_source_y: -0.16,
    default_source_x: 1.002,
    xanchor: 'right',
    yanchor: 'top',
    showarrow: false,
    chart_source_x: 0.0,
    chart_source_y: 0.0,
    chart_source_xanchor: 'left',
    chart_source_yanchor: 'top',
    table_source_x: 0.0,
    table_source_y: -0.12,
    table_xanchor: 'left',
    table_yanchor: 'top',
  },
  axes: {
    linecolor: 'rgb(38, 38, 38)',
    tickcolor: 'rgb(38, 38, 38)',
    gridcolor: 'rgb(38, 38, 38)',
    showgrid_x: false,
    showgrid_y: true,
    ticks: 'outside',
    tickwidth: 2,
    showline: true,
    linewidth: 2.5,
    zeroline: true,
    zerolinewidth: 2.5,
    zerolinecolor: 'rgb(38, 38, 38)',
    showspikes: true,
    spikethickness: 2.4,
    spikedash: 'dot',
    spikecolor: 'rgb(38, 38, 38)',
    spikemode: 'across',
    x_title_text: '',
    x_ticklen: 6,
    x_nticks: 15,
    x_tickformat: '%d %b %y',
    y_primary_title_text: '',
    y_primary_tickformat: ',d',
    y_primary_ticksuffix: '',
    y_primary_tickprefix: '',
    y_primary_range: null,
    y_secondary_title_text: '',
    y_secondary_tickformat: ',d',
    y_secondary_ticksuffix: '',
    y_secondary_tickprefix: '',
    y_secondary_range: null,
    gridwidth: 2.5,
    y_showgrid: true,
    y_gridcolor: 'rgb(38, 38, 38)',
    x_gridcolor: 'rgb(38, 38, 38)',
    titlefont_size: 14.4,
    titlefont_color: '#adb0b5',
  },
  plot_specific: {
    scatter: {
      line_width: 4.2,
      mode: 'lines',
      default_fill_mode: null,
      default_fill_color: null,
      line_shape: 'spline',
      line_smoothing: 0.3,
      use_background_image: true,
    },
    metric_share_area: {
      stackgroup: 'one',
      y_tickformat: '.0%',
      y_range: [0, 1],
      legend_marker_symbol: 'circle',
      use_background_image: true,
    },
    bar: {
      bargap: 0.15,
      use_background_image: true,
    },
    horizontal_bar: {
      orientation: 'h',
      textposition: 'outside',
      default_y_column: 'category',
      default_x_column: 'value',
      default_sort_ascending: false,
      bar_height: 0.7,
      bargap: 0.15,
      yaxis_automargin: true,
      use_background_image: true,
    },
    multi_bar: {
      default_scale_values: true,
      default_show_bar_values: false,
      default_tick_frequency: 1,
      barmode: 'group',
      bargap: 0.15,
      bargroupgap: 0.1,
      orientation: 'v',
      textposition: 'outside',
      legend_marker_symbol: 'circle',
      use_background_image: true,
    },
    stacked_bar: {
      default_sort_descending: false,
      barmode: 'stack',
      bargap: 0.15,
      bargroupgap: 0.1,
      default_scale_values: true,
      y_tickformat: ',.0f',
      legend_marker_symbol: 'circle',
      use_background_image: true,
    },
    // Table plot configuration
    table: {
      header_fill_color: '#2a2a2a', // Use primary color
      cell_fill_color_odd: '#1A1A1A', // Slightly off-background
      cell_fill_color_even: '#1A1A1A', // Background color
      line_color: '#404040', // Dark grey lines
      cell_height: 60,
      // Font keys are optional; fallback logic in core.py
      // header_font_key: 'table_header',
      // cell_font_key: 'table_cell',
    },
  },
};